### ISSUE TITLE
[1.16.5] Infinity Drill area does not work with  @Astral Sorcery Marble

### ISSUE THREAD

**Issue by CritonDE** [InnovativeOnlineIndustries/Industrial-Foregoing#1008]
Industrial Foregoing Version: industrial-foregoing-1.16.5-3.2.9.1-fbef27c

The Infinity Drill area does not work with  @Astral Sorcery Marble.

The are effect just ignores the Marble.
![2021-02-07_20 57 14](https://user-images.githubusercontent.com/31478641/107157913-1cd2a380-6987-11eb-96a3-3d7cac64eea0.jpg)

**Comment by noahc3** [comment]
Also came across this; looks like this is because Astral Sorcery defines Marble with its own material type which is not in the Infinity Drill's whitelist.

https://github.com/HellFirePvP/AstralSorcery/blob/1.16-indev/src/main/java/hellfirepvp/astralsorcery/common/block/properties/PropertiesMarble.java#L26
https://github.com/HellFirePvP/AstralSorcery/blob/a6af6c8bd95f49d92acce0bb213e9ec5f931c7ed/src/main/java/hellfirepvp/astralsorcery/common/lib/MaterialsAS.java#L24

Should be fixable with a feature plugin. Not sure how the dev's would want that handled with the current array of whitelisted materials, otherwise I'd submit a PR.
