### ISSUE TITLE
please make the Dissolution chamber have an inventory that you can click on with JEI or internal so that you can select a recipie and pull in items automatically

### ISSUE THREAD

**Issue by soundtechscott** [InnovativeOnlineIndustries/Industrial-Foregoing#1018]
Dissolution Chamber is such trash... doesnt fit the mod at all..... dont even know why you added it...

but since you have it....
how about we improve it and make it less of a pain in the butt to use...

how about a way to click on the recipe you want to use and allow it to auto import items from an internal inventory..
or just make it work like a crafting table and you can click the item and as long as its in your inventory, it populates the table automatically

Its such garbage to have to manually put each item into it one at a time 

or make a recipe card for it so you have to craft the recipe card first before it will auto import...
I mean.. you cant point your ME/Refined storage system at it, cant use hoppers to fill it...

please do something to make this machine better and  more usable

**Comment by Buuz135** [comment]
SINCE I have it I see that you didn't even try to use it. Lets analyze each line:

> Dissolution Chamber is such trash... doesnt fit the mod at all..... dont even know why you added it...

Its my mod I can do whatever I want.

> how about a way to click on the recipe you want to use and allow it to auto import items from an internal inventory..
or just make it work like a crafting table and you can click the item and as long as its in your inventory, it populates the table automatically ... Its such garbage to have to manually put each item into it one at a time

The machine can pull from any inventory and the items can go in any slot.

> or make a recipe card for it so you have to craft the recipe card first before it will auto import...
> I mean.. you cant point your ME/Refined storage system at it, cant use hoppers to fill it...

Refined Storage works perfectly with the machine without adding any integration thanks to the amazing machine desing that locks the slots when crafting and hoppers work very good with it too.

> please do something to make this machine better and more usable

Since you asked so _nicely_, I won't. Thanks for using my mod.
