### ISSUE TITLE
[1.16]  Plant sower filters doesn't work with Insanium Farmland & Mystical Agriculture

### ISSUE THREAD

**Issue by Jsalvat** [InnovativeOnlineIndustries/Industrial-Foregoing#1194]
**Industrial Foregoing Version:**
industrial-foregoing-1.16.5-3.2.14.6-14

I'm playing in the Oceanblock Modpack. It seems that filtering by colours doesn't work. It just plants wherever he wants.

**Comment by Jizanthapus** [comment]
Different modpack, but I am also seeing this issue

**Comment by davidthehat** [comment]
I think this is intended behavior. On every work cycle, the Plant Sower checks the filtered item for the position it wants to plant in next. If the slot is empty, it simply plants the first available seed.

https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/blob/1.16/src/main/java/com/buuz135/industrial/block/agriculturehusbandry/tile/PlantSowerTile.java#L95

As a workaround, fill the empty filter slots with dummy items. Also, I don't think this has anything to do with Insanium Farmland or Mystical Agriculture.

**Comment by Agent-coulson** [comment]
I have the same issue, only with atm7 ver 0.4.32. firstly it seems that the plant sower does not stick to it's specified areas. tested it, and it just seems to plant wherever it wants to. I know this happens because, oddly, whenever I try and put a different Mystical Agriculture(MA) seed in for a different area, for some reason it picks the same spot as a previously planted MA seed, and tries to plant it there, breaking the old plant and dropping both seeds on the ground. secondly, the plant gatherer seems to be veeery finicky as far as harvesting MA plants. it will only harvest them if there's another plant in the working area? if there is only one plant, it will not harvest it. ever.
