### ISSUE TITLE
[1.19] Cannot open infinity backpack with keybind; keybind missing

### ISSUE THREAD

**Issue by Jack-McKalling** [InnovativeOnlineIndustries/Industrial-Foregoing#1340]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**
check
**Industrial Foregoing Version:**
industrial-foregoing-1.19.2-3.3.2.2-4
**Titanium Version:**
titanium-1.19.2-3.7.2-26
**Crashlog If Applicable (Upload to pastebin/gist):**
n/a

If you open the keybinds menu to (re)configure the key for opening the Infinity Backpack, the keybind is missing from the menu.
If you copy the keybind from options.txt from a 1.18.2 version, it still doesn't work.

So the entire keybind is broken, not just missing from the menu.

On the 1.19 (nondefault) branch, I found a [reference to the keybind](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/blob/4ec88a2161b13b335669de9035ca493d0ee9fce6/src/main/java/com/buuz135/industrial/proxy/client/ClientProxy.java#L93)
`OPEN_BACKPACK = new KeyMapping("key.industrialforegoing.backpack.desc", -1, "key.industrialforegoing.category");`

and the [keybind itself](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/blob/4ec88a2161b13b335669de9035ca493d0ee9fce6/src/main/resources/assets/industrialforegoing/lang/en_us.json#L10).
`  "key.industrialforegoing.backpack.desc": "Open Infinity Backpack",`

However I cannot tell what's wrong by these.

**Comment by XFactHD** [comment]
Since the issue author mentioned this on the Forge Discord, I took a look at the referenced keybind registration. The cause for the keybind not being registered is that the `RegisterKeyMappingsEvent` handler is being registered to the wrong bus, that event fires on the mod bus and not on the Forge bus: https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/blob/1.19/src/main/java/com/buuz135/industrial/proxy/client/ClientProxy.java#L94
