### ISSUE TITLE
[1.20] Draconium Tag is Wrong.

### ISSUE THREAD

**Issue by KodYazanDruid** [InnovativeOnlineIndustries/Industrial-Foregoing#1417]
https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/blob/1.20/src/generated/resources/data/industrialforegoing/recipes/laser_drill_ore/ores/draconium.json

I already pinged Buuz on discord but i am opening an issue to not forget.

**Comment by Vadis0H** [comment]
friends, I’m sorry that I didn’t find this bug earlier, although I could have done it back in 2023 on 11.20, if you see inconsistencies, don’t be afraid to go to the recipe directory and find any bugs, you will help people a lot. So that you understand, I found it while studying the mod for changing crafts and found a mismatch, and then decided to check why this was so. Hello everyone, and special thanks to the developers of this mod for their quick response
![image](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/assets/51758510/e5fff7e3-3406-4548-8c98-ed83a49e8309)

**Comment by Buuz135** [comment]
Fixed in https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/commit/6f35f9686b6b28bf8648b6c2f4acb2f1c7c9bebc I didnt change the commit message
