### ISSUE TITLE
[Bug] Liquid XP into Black Hole Tank

### ISSUE THREAD

**Issue by PotatoFlavour** [InnovativeOnlineIndustries/Industrial-Foregoing#435]
Hi,

I'm playing on a multicraft server with a friend. The server has FTB Revelation 2.5.0 running.

For a couple of weeks I've been trying to find a solution for a compact XP storage instead of spamming tanks through my basement. I figured the best solution is to get Liquid XP into a Black Hole Tank. I thought of this solution 3 versions of FBT ago. Since then, after every update I once again tried to insert Liquid XP into a Black Hole Tank. Unfortunately, it always resulted in the same bug: server crash. I tried to insert it with a Bucket of Liquid XP. I figured if I'd try an automated way we might not be able to get the server running again, because every time it crashed, we had to run "Remove erroring tile entities" in order to fix it. I've tried the same in single player and for some reason it worked. So it seems to be only crashing multiplayer servers.

I figured I wouldn't be the only one struggling with this so I just assumed it would be fixed in next updates, but since it still hasn't, I decided to finally address it. I hope I've been clear enough in order to be able to create a solution for this. If you have any questions I'll try to answer them. If you need any versions please explain where I can find which versions I'm using.

Edit: the Liquid XP Bucket is from Open Blocks, by the way, but since the Black Hole Tank is the only container (that I know of) not being compatible, I decided to address it here.

Industrial Foregoing Version:
TeslaCoreLib Version: 
Crashlog (If Any):

**Comment by Buuz135** [comment]
What is the crash?

**Comment by PotatoFlavour** [comment]
> What is the crash?

It takes the whole server offline. We need to run "Remove erroring tile entities" to fix it.

This is a crashlog from a crash by the same cause, a (couple of) versions ago https://gist.github.com/kevinvdburgt/fd324f4b979cb546b368b9d8314f98ec

**Comment by BrisingrAerowing** [comment]
This is a Tesla Core Lib bug (though why it happens is the question, as the crash is guarded against). See MinecraftModDevelopmentMods/Tesla-Core-Lib#28

Also see #413

**Comment by Drathonix** [comment]
Posting this here for anyone who googles the crash log and inevitably ends up here.
Since I could not find a fix, I decided to experiment. The problem lies in the OpenBlocks "XP Bucket". The good news is that this item can be disabled and replaced with another that does not crash the game.

**To fix the problem**, in the openblocks.cfg file under the section "items" change the boolean "xp_bucket" to false. This will prevent the broken XP bucket from being registered into the game, which means that forge will send the missing registry warning upon loading a world created before the fix, any XP buckets in that world will be deleted. As for the replacement item, it already exists, it is called the "Liquid XP Bucket", it has the same functionality as the broken bucket but does not cause the crash issue and will be used instead of the broken bucket by default.

It is also notable that worlds which had been affected by this problem will become playable again.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
