### ISSUE TITLE
[1.15.2] crash/error

### ISSUE THREAD

**Issue by Quu1337** [InnovativeOnlineIndustries/Industrial-Foregoing#684]
Industrial Foregoing Version: industrial-foregoing-1.15.2-2.2.1-f27c515.jar
TeslaCoreLib Version: 
Crashlog (If Any):  https://pastebin.com/3FkKeefz

**Comment by mbainter** [comment]
Industrial Foregoing Version: industrial-foregoing-1.15.2-2.2.2-28d4a81
TeslaCoreLib Version: 
Crashlog (If Any): 
[crash-2020-04-10_13.15.14-client.txt](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/4465393/crash-2020-04-10_13.15.14-client.txt)

Ran into the same "UnsupportedOperationException: No bounds for empty shape" error.  This was triggered by the player mining in the Nether with an infinity drill, instead of against a bubble column.  Like in #688, player is unable to reconnect after the initial disconnect, always fails with the above crash report.

**Comment by Buuz135** [comment]
This should be fixed already
