### ISSUE TITLE
Dissolution Chamber allows too many items to be inserted which stops the craft

### ISSUE THREAD

**Issue by guvnor33** [InnovativeOnlineIndustries/Industrial-Foregoing#745]
Industrial Foregoing Version: 2.3.0
TeslaCoreLib Version: 
Crashlog (If Any): 

Trying to automate the dissolution chamber, my recipe calls for 1 item and a liquid, but the chamber allows many of the same item to be inserted, and unfortunately, as soon as there are two or more of the item in slots, the craft stops.  Can I lock out the other slots?  Or, how would I do this? I want to automate this using Refined Storage. thank you

**Comment by Pulimer** [comment]
I have found a good solution. I am not 100% sure if it is fully stable. It works, however, it seems that, because I am using a hopper, that unloading the chunks or generally going too far away causes it to break. Never close by though. Anyway, it works like this: You connect the chamber via external storage to your storage system, and also whitelist glass panes in the external storage gui. You have the hopper facing into one of the sides of the chamber. Connect necessary energy source, exporters, and importers to the chamber, however, no exporter for items. You need one detector, place it adjacent to the hopper and connected to any cable or other part of the system. Tell the detector to give off a redstone signal if there is more than 0 glass panes in the storage system. Finally, let an exporter run into your hopper, and whitelist glass panes. Through the external storage, the dissolution chamber's inventory is connected to the storage system, however, the hoppers is not. If there are any glass panes anywhere in the system the hopper is locked, but items still can be transported into the hopper via the exporter. Then, if the exporter exports all glass panes out of the system into the hopper there will be no glass panes in the storage system, the detector turns off, and unlocking the hopper. The hopper then sends glass panes into the chamber, and because the chamber is part of the storage system via the external storage, the detector detects more than 0 glass panes in the system, and again, locks the hopper, until there are no more glass panes, that is if the dissolution chamber has used one up. Optionally add a lever to the exporter of the hopper, to lock it, if you do not want the automatic process, or simply have no glass panes in the system. Also, with this you cannot have more than five stacks of glass panes in the storage system, or you have to add additional storage via a chest or similar, except anything from main storage system. The exporter then would have to go into that additional storage. 
I hope you can use this.

**Comment by 0xicl33n** [comment]
After reading that extremely long post and having no idea what it meant, i took matters into my own hands. it uses a dropper/hopper tower and goes from the bottom up. I hope this helps someone else.



https://user-images.githubusercontent.com/2192160/103467523-bd88d000-4d04-11eb-9f5d-275272cb4a8c.mp4
