### ISSUE TITLE
[1.12] Plant Gatherer has no limits and "gathers" my entire base.

### ISSUE THREAD

**Issue by staviq** [InnovativeOnlineIndustries/Industrial-Foregoing#887]
**Industrial Foregoing Version:**
industrialforegoing-1.12.2-1.12.13-237
**TeslaCoreLib Version:**
tesla-core-lib-1.12.2-1.0.17

Modpack E2E.

Plant Gatherer has no limits and goes ham on absolutety any tree-like block around.

I grew a tree and it so happened, it's leaves touched a piece of my base structure that was made of a log, and the plant gatherer decided that my entire base that is roughly 3x3 chunks, is a tree. Even though its made of entirely diffrent type of wood.

No range modules installed.

Once i realised what was going on, a tree on the other side of the base was already stripped of it's leaves: ( plant gatherer on the right, with a small tree that it was supposed to gather, big silverwood tree on the far left )

https://i.imgur.com/vbAmrhE.jpg

And a short time later:

https://i.imgur.com/FQUukyy.jpg

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.

**Comment by ranger135xp** [comment]
I totally understand moving onto the new versions and limiting the amount of work and support needed, since you do this for fun or a myriad of personal reasons. We appreciate that!
This bug is quite a nasty one. At least come back and address anything of this criticality.
I remember when in 1.7.10, the last update for ComputerCraft by Dan200 was one that fixed a very critical issue, but then broke the ability to use bundled cable from ProjectRed. I get there's a time to move on, but something like that really sucks when it happens.
Would you please reconsider?

If not, are you willing to hand the reigns over to someone who would fix it for 1.12.2 since it's very much alive and receiving community updates?
